Testing Review for Swirl Protocol
best-practicers/reviews pull request #19
Opened 2021-02-18 22:22 UTC by hollygrimm

Let me know if you have suggestions or changes!

2021-02-22 05:57 UTC, carlfarterson requested changes

2021-02-22 05:57 UTC, carlfarterson commented on reviews/swirl-protocol/testing/README.md
> +ALl the integration tests call `resetFork()` from `utils\integration.ts` which uses Alchemy to fork from a specific block number.
"ALl" to "All" and `utils\integration.ts` to `utils/integration.ts`

2021-02-22 05:57 UTC, carlfarterson commented on reviews/swirl-protocol/testing/README.md
> +
Can remove these extra lines

2021-02-22 05:57 UTC, carlfarterson commented on reviews/swirl-protocol/testing/README.md
> +Tests using the chai matchers `calledOnContract` and `calledOnContractWith` have been separated out into separate files suffixed 'WithMock'. These tests are utilizing the waffle provider directly. Se
Can we hyperlink "here"

2021-02-23 01:00 UTC, carlfarterson approved these changes

2021-02-23 15:29 UTC, TSnark approved these changes

2021-02-28 22:16 UTC, merged